name: deployment pfg-frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cp /home/gonzalo/pfg/pfg-frontend/static/config.js /home/gonzalo/pfg/pfg-frontend/actions-runner/_work/PFG-frontend/PFG-frontend/src/config.js
    - run: npm ci
    - run: npm run build