name: deployment pfg-frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cp /home/gonzalo/pfg/pfg-frontend/static/config.js /home/gonzalo/pfg/pfg-frontend/actions-runner/_work/PFG-frontend/PFG-frontend/src/config.js
    - run: yarn install
    - run: yarn run build --if-present
    - run: cd /home/gonzalo/pfg/pfg-frontend/actions-runner/_work/PFG-frontend/PFG-frontend/build
    - run: pm2 restart pfg-frontend